// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCRkRiYgChDZ6I2-GIc-f3DXOvK_9HfKw',
    appId: '1:902225415317:web:13fe5b3bb17315cced9f9c',
    messagingSenderId: '902225415317',
    projectId: 'zivoro-erp-app',
    authDomain: 'zivoro-erp-app.firebaseapp.com',
    storageBucket: 'zivoro-erp-app.firebasestorage.app',
    measurementId: 'G-PQZVXWNR6X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaFeSjNhe7vSu4hRTv2EQO0LWOrfgkIcc',
    appId: '1:902225415317:ios:1dbe92ffb7b86ebfed9f9c',
    messagingSenderId: '902225415317',
    projectId: 'zivoro-erp-app',
    storageBucket: 'zivoro-erp-app.firebasestorage.app',
    iosBundleId: 'com.example.posBilingFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCRkRiYgChDZ6I2-GIc-f3DXOvK_9HfKw',
    appId: '1:902225415317:web:dcc64966ac72f053ed9f9c',
    messagingSenderId: '902225415317',
    projectId: 'zivoro-erp-app',
    authDomain: 'zivoro-erp-app.firebaseapp.com',
    storageBucket: 'zivoro-erp-app.firebasestorage.app',
    measurementId: 'G-FZGLYQL9ZS',
  );
}
